local_costmap:
   global_frame: odom
   robot_base_frame: robot_footprint
   update_frequency: 0.3
   publish_frequency: 0.1
   width: 5.0
   height: 5.0
   resolution: 0.05
   static_map: false
   rolling_window: true
